language: java
os: osx
before_install:
  - brew cask install java
  - git config --global user.email "travis-ci@travis-ci.com"
  - git config --global user.name "Travis CI"
  - ./paper patch
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work'
